import type { CSSProperties } from "react";

/** Co-located styles for the Agent Editor CI tab (mock 02-agent-ci-tab.png). */
export const s = {
  wrap: { maxWidth: 860 } satisfies CSSProperties,

  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 20,
    flexWrap: "wrap" as const,
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    minWidth: 0,
  } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap" as const,
  } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  activeBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 10px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600,
    color: "var(--ok)",
    background: "var(--ok-bg)",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  } satisfies CSSProperties,

  failOnSection: {
    marginBottom: 20,
    maxWidth: 420,
  } satisfies CSSProperties,

  list: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  } satisfies CSSProperties,
  row: {
    display: "grid",
    gridTemplateColumns: "minmax(160px, 1.4fr) minmax(120px, 1fr) auto auto",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  repoCell: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  repoLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
    color: "var(--text-primary)",
    textDecoration: "none",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    fontWeight: 500,
  } satisfies CSSProperties,
  repoName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  targetCell: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
    minWidth: 0,
  } satisfies CSSProperties,
  targetLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  statusCell: {
    justifySelf: "end",
  } satisfies CSSProperties,
  timeCell: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap" as const,
    justifySelf: "end",
    minWidth: 56,
    textAlign: "right" as const,
  } satisfies CSSProperties,

  addRow: {
    marginTop: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "14px 16px",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    width: "100%",
  } satisfies CSSProperties,

  empty: {
    padding: "20px 14px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center" as const,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    marginBottom: 8,
  } satisfies CSSProperties,
  loading: {
    padding: "20px 14px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center" as const,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
} as const;
