import type { CSSProperties } from "react";

/** Co-located styles for AgentRunPicker. */
export const s = {
  root: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", justifyContent: "space-between" } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  headerLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.02em",
  } satisfies CSSProperties,
  clearLink: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--accent-text)",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
  } satisfies CSSProperties,
  rowIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  rowBody: { display: "flex", flexDirection: "column", minWidth: 0, flex: 1 } satisfies CSSProperties,
  rowName: {
    fontSize: 13.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowGist: {
    fontSize: 12,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowHint: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0, whiteSpace: "nowrap" } satisfies CSSProperties,
  emptyRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    color: "var(--text-muted)",
    fontSize: 13,
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  footer: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  footerRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  totals: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  configureLink: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
} as const;
