import type { CSSProperties } from "react";

/** Co-located styles for the skill Context section (mirrors the agent
    ContextTab/styles.ts row pattern, plus a "SERIALIZES AS" block). */
export const s = {
  wrap: { maxWidth: 760, marginTop: 32 } satisfies CSSProperties,
  header: { marginBottom: 16 } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "baseline", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  tokenTotal: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", margin: "0 0 12px" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginTop: 8 } satisfies CSSProperties,
  list: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  rowFirst: { borderTop: "none" } satisfies CSSProperties,
  rowDragging: { opacity: 0.4 } satisfies CSSProperties,
  handle: {
    cursor: "grab",
    color: "var(--text-muted)",
    fontSize: 15,
    lineHeight: 1,
    userSelect: "none",
    width: 16,
    textAlign: "center",
  } satisfies CSSProperties,
  handleDisabled: { cursor: "default", opacity: 0.3 } satisfies CSSProperties,
  checkbox: { cursor: "pointer", width: 15, height: 15, accentColor: "var(--accent)" } satisfies CSSProperties,
  path: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  empty: {
    padding: "18px 14px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center",
  } satisfies CSSProperties,
  serializeBlock: { marginTop: 16 } satisfies CSSProperties,
  serializeHeader: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 6,
    textTransform: "uppercase" as const,
  } satisfies CSSProperties,
  serializePre: {
    margin: 0,
    padding: "14px 16px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
    fontFamily: "var(--font-mono, monospace)",
    maxHeight: 280,
    overflow: "auto",
  } satisfies CSSProperties,
} as const;
