import type { CSSProperties } from "react";

export const s = {
  section: { marginBottom: 16 } satisfies CSSProperties,
  roleHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 4px",
    cursor: "pointer",
  } satisfies CSSProperties,
  roleSwatch: (color: string): CSSProperties => ({
    width: 10,
    height: 10,
    borderRadius: 3,
    background: color,
    flexShrink: 0,
  }),
  roleTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  roleSubtitle: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  roleCount: { fontSize: 12, color: "var(--text-muted)", marginLeft: "auto" } satisfies CSSProperties,
  roleChevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .15s",
    flexShrink: 0,
  }),
  fileCard: {
    border: "1px solid var(--border)",
    borderRadius: 7,
    overflow: "hidden",
    background: "var(--bg-elevated)",
    marginBottom: 6,
  } satisfies CSSProperties,
  fileHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    cursor: "pointer",
  } satisfies CSSProperties,
  fileBody: {
    borderTop: "1px solid var(--border)",
    padding: "8px 0",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  filePath: {
    fontSize: 13,
    flex: 1,
    minWidth: 0,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  fileStat: { fontSize: 12.5, whiteSpace: "nowrap", flexShrink: 0 } satisfies CSSProperties,
  addText: { color: "var(--ok)" } satisfies CSSProperties,
  delText: { color: "var(--crit)" } satisfies CSSProperties,
  findingDot: {
    width: 7,
    height: 7,
    borderRadius: 99,
    background: "var(--warn)",
    flexShrink: 0,
  } satisfies CSSProperties,
  codeLineWrap: (stripeColor: string | null): CSSProperties => ({
    borderLeftWidth: stripeColor ? 3 : 0,
    borderLeftStyle: "solid",
    borderLeftColor: stripeColor ?? "transparent",
  }),
  findingBadgeButton: {
    background: "none",
    border: "none",
    padding: "0 10px",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
  } satisfies CSSProperties,
  emptyRole: { fontSize: 12.5, color: "var(--text-muted)", padding: "6px 12px" } satisfies CSSProperties,
  splitBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 8,
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
    marginBottom: 16,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
