import type { CSSProperties } from "react";

export const s = {
  pageHeader: { marginBottom: 28 } satisfies CSSProperties,
  pageTitle: { fontSize: 22, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  pageSubtitle: {
    fontSize: 13.5,
    color: "var(--text-secondary)",
    marginTop: 6,
    maxWidth: 640,
  } satisfies CSSProperties,
  step: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 24 } satisfies CSSProperties,
  stepHeader: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  stepBadge: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    fontSize: 11,
    fontWeight: 700,
    background: "var(--accent)",
    color: "#fff",
  } satisfies CSSProperties,
  stepBadgeMuted: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    fontSize: 11,
    fontWeight: 700,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  stepLabel: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  stepLabelMuted: { fontSize: 13.5, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  agentsCard: {
    minHeight: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
  runAgain: {
    marginTop: 16,
    padding: "6px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "transparent",
    border: "1px solid var(--border-strong)",
    borderRadius: 7,
    cursor: "pointer",
  } satisfies CSSProperties,
} as const;
