import type { CSSProperties } from "react";

/** Co-located styles for the Agent Editor Evals tab. */
export const s = {
  wrap: { maxWidth: 820 } satisfies CSSProperties,

  // ── Metrics section ──────────────────────────────────────────────────────────
  metricsSection: { marginBottom: 28 } satisfies CSSProperties,
  metricsHeader: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    marginBottom: 14,
  } satisfies CSSProperties,
  metricsTitle: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  metricsSubtitle: {
    display: "block",
    fontSize: 13,
    color: "var(--text-muted)",
    marginBottom: 14,
    marginTop: -6,
  } satisfies CSSProperties,
  /** Version-skew warning — mirrors EvalCaseModal.warnBanner. */
  staleBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 14px",
    borderRadius: 8,
    background: "var(--warn-bg, rgba(234,179,8,0.10))",
    color: "var(--warn, #ca8a04)",
    fontSize: 12,
    lineHeight: 1.5,
    marginBottom: 14,
  } satisfies CSSProperties,
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 12,
  } satisfies CSSProperties,
  metricCard: {
    background: "var(--bg-surface)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    padding: "14px 16px",
  } satisfies CSSProperties,
  metricLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.07em",
    color: "var(--text-muted)",
    textTransform: "uppercase" as const,
    marginBottom: 8,
  } satisfies CSSProperties,
  metricValue: {
    fontSize: 26,
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1,
    marginBottom: 6,
  } satisfies CSSProperties,
  metricUnavailable: {
    fontSize: 22,
    fontWeight: 500,
    color: "var(--text-muted)",
    lineHeight: 1,
    marginBottom: 6,
  } satisfies CSSProperties,
  metricDelta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 12,
  } satisfies CSSProperties,
  metricDeltaPositive: { color: "#22c55e" } satisfies CSSProperties,
  metricDeltaNegative: { color: "var(--crit)" } satisfies CSSProperties,
  metricDeltaNeutral: { color: "var(--text-muted)" } satisfies CSSProperties,

  // ── Cases section ────────────────────────────────────────────────────────────
  casesHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  } satisfies CSSProperties,
  casesLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  casesTitle: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  passingCount: {
    fontSize: 12,
    fontWeight: 600,
    color: "#22c55e",
    background: "rgba(34, 197, 94, 0.12)",
    padding: "2px 9px",
    borderRadius: 999,
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  /** Shown when no case has been scored on the current agent version. */
  notScoredCount: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--warn, #ca8a04)",
    background: "var(--warn-bg, rgba(234,179,8,0.12))",
    padding: "2px 9px",
    borderRadius: 999,
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  casesRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  } satisfies CSSProperties,
  card: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  statusIcon: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 18,
    height: 18,
  } satisfies CSSProperties,
  statusPassed: { color: "#22c55e" } satisfies CSSProperties,
  statusFailed: { color: "var(--crit)" } satisfies CSSProperties,
  statusNever: {
    width: 14,
    height: 14,
    borderRadius: 99,
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: "var(--text-muted)",
    opacity: 0.55,
    boxSizing: "border-box" as const,
  } satisfies CSSProperties,
  cardBody: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  } satisfies CSSProperties,
  cardName: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  cardSubtitle: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  cardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  } satisfies CSSProperties,
  badges: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap" as const,
    justifyContent: "flex-end",
  } satisfies CSSProperties,
  badge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 9px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.02em",
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    whiteSpace: "nowrap" as const,
  } satisfies CSSProperties,
  badgeEmpty: {
    fontFamily: "var(--font-mono, monospace)",
    fontWeight: 500,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  cardActions: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  } satisfies CSSProperties,
  empty: {
    padding: "20px 14px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center" as const,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  loading: {
    padding: "20px 14px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center" as const,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,

  // ── Footer ───────────────────────────────────────────────────────────────────
  footer: {
    marginTop: 14,
    display: "flex",
    justifyContent: "flex-end",
  } satisfies CSSProperties,
} as const;
